site_name: Project LAB 2016
theme: readthedocs
pages:
- Introduction: index.md
- Examples: examples.md
- Top Level Design: top_level_design.md
- Raspberry Pi: raspberry_pi.md
- Project Requirements: project_requirements.md
- Planning: planning.md
- Final Presentation: final_presentation.md
- Reporting: reporting.md